language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: firebase
  local_dir: build
  token:		
     secure:  LhswWmGyLefpDvaplgEME9RsdqaAqnnTk6bkbS8oA3MK9lR6tbxFOKf2ciYF6Sec9X3hFAeCWzGg3Uab7X8EIcIMI6bJMsaNmYywNXk2OQB4QmuzxqA+SFpJiRdC2g4PhwBcKmMymqHLT3bZcNk52FUvMp/p30FWaTzCWdReKZXkeLNEv5ZXsFLJSMJxqZnBOg0ycT8ml74QgydKS+sqapfvenjJNWQ/fLO3FRLShJv67h0NbXo8yy9U7jCiGuGeqp2IVvzoeV3Q3oCQdzJQhs+n9kqy6oLkGnF1Db+jMi4fa9OuKh7qG/sRW2nIXWuujIjS8IwPqp+oSxnkmidUqPLricoJSQcYw3JNpvaUjWaxZjicscCaZolYvx+3e7bXLtB+N9mjMFlynn9k+cX80LmrlBNqavUlj5dNiteSf4LWC+V4UumDuMUgF6yT05qkalIXWD24/XIZoIfR+L8DukoMTTjqIxxk+IrGqvCh7FNCYOA6ohOWOAihsqn74jQY1hQKGCNK42Rmfcsop51F6S5RVn7AUBurYRgZ4QkyzIRDulPuYR9L+YXwJmHoHPiICCdn1zX8/3mCso0RQ0dmJU5XA7cvxA2vsF7aeei1lLpJYl13Qoe7OEw9oOwjd73SX9Z2WAmJfnnNuvM8KiGMxH4vwXEqyraEJ1oX3FQsdsc=
env:
  global:
    secure: LhswWmGyLefpDvaplgEME9RsdqaAqnnTk6bkbS8oA3MK9lR6tbxFOKf2ciYF6Sec9X3hFAeCWzGg3Uab7X8EIcIMI6bJMsaNmYywNXk2OQB4QmuzxqA+SFpJiRdC2g4PhwBcKmMymqHLT3bZcNk52FUvMp/p30FWaTzCWdReKZXkeLNEv5ZXsFLJSMJxqZnBOg0ycT8ml74QgydKS+sqapfvenjJNWQ/fLO3FRLShJv67h0NbXo8yy9U7jCiGuGeqp2IVvzoeV3Q3oCQdzJQhs+n9kqy6oLkGnF1Db+jMi4fa9OuKh7qG/sRW2nIXWuujIjS8IwPqp+oSxnkmidUqPLricoJSQcYw3JNpvaUjWaxZjicscCaZolYvx+3e7bXLtB+N9mjMFlynn9k+cX80LmrlBNqavUlj5dNiteSf4LWC+V4UumDuMUgF6yT05qkalIXWD24/XIZoIfR+L8DukoMTTjqIxxk+IrGqvCh7FNCYOA6ohOWOAihsqn74jQY1hQKGCNK42Rmfcsop51F6S5RVn7AUBurYRgZ4QkyzIRDulPuYR9L+YXwJmHoHPiICCdn1zX8/3mCso0RQ0dmJU5XA7cvxA2vsF7aeei1lLpJYl13Qoe7OEw9oOwjd73SX9Z2WAmJfnnNuvM8KiGMxH4vwXEqyraEJ1oX3FQsdsc=