language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
deploy:
  provider: firebase
  local_dir: build
  project: "imagem-8a58a"
env:
  global:
    secure: qO70U4TzjWl43Xk2wjTtx24JcS0Ul36WjtG05CrWx1aSZ1iCTPzzwWGhQyNsum3rldQ/USZ6woTOGw16Nt78Sz6NpMtchpcrReTHJpI4LNf5lSc5zs884QiSZwQRxe1peN6/iahL6IaQXsUVrLEyfM6RUY2AVDBlG1TatPVf5MJh2AySzElAO0UcLKXwGcKKfMrOwhBugk5glcxVqsJkLHOxVLM7UwzH/fLz7C+34mOoheGmRpoyDvYpUgdwTyBcCC7cAqVwGnRLQQB9o66g5jdyQ7LgiyGgLSiUMhcGnxv7Kp2sjbjPUaOmPeAJo5AZbFNJA6pOwEokJbj8a6mrO+zAxCO9p213d7tlxqtneW/2pcp5svGs8LZFg/noU6qqhjZ3y3wP/44W0+pIIJ48Pe9J5kD7HIiq2BRaiTd5c9Sb/cyzeh68/i3Tr84VrgXzW9zM0og9qVN+yyLqitgzC33ZM/UXCvopwTD9Rqzsk4Z3KgMRpwOc8bTcmG6eYz4IyRXACkBEqwmpW/C41B6pW8yUU8KDyXDzMoA000ZrgUS5IxcdwQRRfRswJqZk5k2tQnyiTETHQLO22azVk4TEutjzjOBzw1p/TERLN4HMAu+49TsZ+hwSMODuVBCknT00oKX87WFJnin+pd3uFF85Qamq+RIzgSbwzf+lk//7Wlc=
